### ISSUE TITLE
Box-sizing

### ISSUE THREAD

**Issue by baut0015** [baut0015/sections#1]
I can't figure out what is left in this assignment. I've tried all the sizes provided and added width/ max width, changing in dev tools to try to match the picture and get an idea of the size, but I can't figure out what to do. 
Help.

@thomasjbradley

**Comment by thomasjbradley** [comment]
There seems to be much more code than necessary. When we looked at this thing on the board we were going to add the `inline-block` & `max-width` & `padding` to the `<div>` tags—but it seems to be on lots of other elements.

**Comment by baut0015** [comment]
Thank you it worked out in the end after deleting some code and messing around with sizes.
